### PR TITLE
Implement padding with silence in pre-process

### PR DESCRIPTION
**Pull request by kasbah**
This pads the length with silence and adds silent channels to fit all files to the maximums. It addresses #1.

I don't know whether this would work for augmentation. Please check if the changed wording in the README is correct.

### CODE REVIEW

**Comment by kasbah** [comment]
Padding still needs to be done for `predict_class.py`.

**Comment by kasbah** [comment]
I had forgotten about this too, I can take a look at adding padding to `predict_class.py` if there is a chance of it being merged.

**Comment by drscotthawley** [comment]
@kasbah Thanks for this.  In checking I notice typos preventing execution.  Can you clean up the call to get_canonical_shape()?  e.g.

 ```
 File "./preprocess_data.py", line 34, in find_max_shape
    shapes.append(get_cananonical_shape(signal))
NameError: name 'get_cananonical_shape' is not defined

```

**Comment by kasbah** [comment]
Oops, I think I forgot to test after I tried to fix my spelling. Should be fixed now.

**Comment by drscotthawley** [comment]
Great!  First merge!  And actually, I just added a feature where you can set the maximum-allowed clip length as well.  I have a use case with many many small files and few long files.  the padding was producing tons of long files. the max length allows you to truncate the long file.  standby for an update on that soon.  (it'll be an option)

**Comment by kasbah** [comment]
Should I do anything about predict_class.py?

**Comment by drscotthawley** [comment]
@kasbah Yes, predict_class should probably pad or truncate as needed, based on the size of the input layer of the network. 

Also: I'm thinking of making find_max_shape() *not* be executed by default, and instead making it enabled with a --findmax flag,  because I dislike how it slows down execution for my (carefully pre-homogenized) datasets. Which is why I added the --clean option, for myself, but I'm not sure I want to have to remember to do that every time. ;-)    Also I had to add the --dur flag because find_max_shape() was padding huge amounts of silence to short clips, and I needed to truncate.  I'm not sure what the default should be.

One 'graceful and fast' way of operating would be to make everything like the first file, and pad or truncate as needed; that way at least people wouldn't be having issues.  And then if they want to do find_max_shape, they can enable --findmax.

Not changing anything yet. Just thinking about it.

**Comment by kasbah** [comment]
I think the least confusing behaviour is the find-max-shape behaviour so I would keep that as the default and offer the others as optimizations behind flags. Of course, it's your project, so you are BDFL and can specialize it for your own use cases as much as you wish. 😄 

I'll take a look adding padding to predict_class when I get a chance.

**Comment by drscotthawley** [comment]
All right I'll keep the behavior, thanks for the feedback.

And I'm about to update predict_class for a different reason -- I've changed the model saving & loading routines so that it will encode the class names inside the weights.hdf5 file.   Previously it was looking at the names of directories (which it no longer needs, and ideally may never have access to) to get the directory names.

**Comment by drscotthawley** [comment]
Ok I made the change to predict_class.py so that it auto pads or truncates relative to the network input size, and it reads class names from the weights.hdf5 file  (not this is not backwards-compatible with previous weights files)
Currently in dev branch, will probably pull to master soon: https://github.com/drscotthawley/panotti/blob/dev/predict_class.py

**Pull request merged**
